import './globals.css'
import type { Metadata } from 'next'
import { AppBar } from '@/components/appBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-black-900 text-light-gray' style={{
        height: '100vh',
        margin: 0,
        padding: 0,
        overflowY: 'auto',
      }}>
        <AppBar />
        {children}
      </body>
    </html>
  )
}
